### ISSUE TITLE
Improve initiative tracker

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#45]
Additional features desired for a 1.0 release:
- [X] Provide a 'next turn' button and show who is currently acting
- [X] Provide a total number of rounds counter
- [X] Provide the ability to start an additional round counter
    - e.g. to keep track of the duration of certain spells
- [X] Highlight token on hover in initiative list

Optionally
- [ ] Other sorting methods

**Comment by Kruptein** [comment]
b5a6541e0e6d38e6cebb2a5f79234dafc585eff6 implements a next turn button and shows whose turn it currently is
